/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PollinationsAIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultModel: "openai",
  saveToNotes: true,
  notesFolder: "AI chats",
  apiToken: "",
  imagesFolder: "AI images",
  defaultImageModel: "zimage",
  videosFolder: "AI videos",
  audioFolder: "AI audio",
  defaultVideoModel: "veo",
  language: "en",
  showFreeModelsOnly: false
};
var TRANSLATIONS = {
  en: {
    // Commands
    openAIChat: "Open AI chat",
    quickAIQuestion: "Quick AI question",
    generateAIImage: "Generate AI image",
    generateAIVideo: "Generate AI video",
    generateAIAudio: "Generate AI audio",
    aiChat: "AI chat",
    // Modal titles
    aiChatTitle: "AI chat",
    quickQuestionTitle: "Quick AI question",
    imageGenerationTitle: "Generate AI image",
    videoGenerationTitle: "Generate AI video",
    audioGenerationTitle: "Generate AI audio",
    // Labels
    model: "Model",
    prompt: "Prompt",
    size: "Size",
    yourQuestion: "Your question",
    duration: "Duration (seconds)",
    aspectRatio: "Aspect ratio",
    voice: "Voice",
    attachImage: "Attach image",
    uploadImage: "Upload image",
    // Placeholders
    enterQuestion: "Enter your question...",
    enterPrompt: "Describe the image you want to generate...",
    enterToken: "Enter token...",
    // Buttons
    send: "Send",
    saveChat: "Save chat",
    clear: "Clear",
    ask: "Ask",
    cancel: "Cancel",
    generate: "Generate",
    // Messages
    thinking: "Thinking...",
    noMessages: "No messages to save",
    enterQuestionMsg: "Enter a question",
    enterPromptMsg: "Enter a prompt",
    chatSaved: "Chat saved to",
    saveError: "Save error",
    imageSaved: "Image saved",
    imageError: "Failed to save image",
    videoSaved: "Video saved",
    videoError: "Failed to save video",
    audioSaved: "Audio saved",
    audioError: "Failed to save audio",
    generating: "Generating image...",
    generatingVideo: "Generating video...",
    generatingAudio: "Generating audio...",
    answerSaved: "Answer saved to note",
    unexpectedResponse: "Unexpected API response",
    error: "Error",
    imageUploaded: "Image uploaded",
    // User/AI labels
    user: "You",
    ai: "AI",
    // Settings
    settingsTitle: "Pollinations AI settings",
    defaultModel: "Default model",
    defaultModelDesc: "Select default AI model",
    saveChatsToNotes: "Save chats to notes",
    saveChatsDesc: "Automatically save AI conversations to notes",
    notesFolder: "Notes folder",
    notesFolderDesc: "Folder where AI chats will be saved",
    apiToken: "API token",
    apiTokenDesc: "Access token for API (optional)",
    imagesFolder: "Images folder",
    imagesFolderDesc: "Folder where generated images will be saved",
    defaultImageModel: "Default image model",
    defaultImageModelDesc: "Default model for image generation",
    videosFolder: "Videos folder",
    videosFolderDesc: "Folder where generated videos will be saved",
    defaultVideoModel: "Default video model",
    defaultVideoModelDesc: "Default model for video generation",
    audioFolder: "Audio folder",
    audioFolderDesc: "Folder where generated audio will be saved",
    language: "Language",
    languageDesc: "Interface language",
    showFreeModelsOnly: "Show only free models",
    showFreeModelsOnlyDesc: "Show only models that work without API key",
    // Model categories
    categoryText: "Text",
    categoryImages: "Images",
    categoryVideo: "Video",
    categoryAudio: "Audio",
    // Image models
    imageModelZimage: "Zimage (Default)",
    imageModelFlux: "Flux",
    imageModelTurbo: "Turbo (Fast)",
    imageModelGPT: "GPT Image",
    imageModelKontext: "Kontext",
    imageModelSeeDream: "SeeDream",
    imageModelNanobanana: "Nanobanana"
  },
  ru: {
    // Commands
    openAIChat: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0418\u0418 \u0447\u0430\u0442",
    quickAIQuestion: "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u043E\u043F\u0440\u043E\u0441 \u0418\u0418",
    generateAIImage: "\u0413\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0418\u0418 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
    generateAIVideo: "\u0413\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0418\u0418 \u0432\u0438\u0434\u0435\u043E",
    generateAIAudio: "\u0413\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0418\u0418 \u0430\u0443\u0434\u0438\u043E",
    aiChat: "\u0418\u0418 \u0447\u0430\u0442",
    // Modal titles
    aiChatTitle: "\u0418\u0418 \u0447\u0430\u0442",
    quickQuestionTitle: "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u043E\u043F\u0440\u043E\u0441 \u0418\u0418",
    imageGenerationTitle: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0418\u0418 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F",
    videoGenerationTitle: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0418\u0418 \u0432\u0438\u0434\u0435\u043E",
    audioGenerationTitle: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0418\u0418 \u0430\u0443\u0434\u0438\u043E",
    // Labels
    model: "\u041C\u043E\u0434\u0435\u043B\u044C",
    prompt: "\u041F\u0440\u043E\u043C\u043F\u0442",
    size: "\u0420\u0430\u0437\u043C\u0435\u0440",
    yourQuestion: "\u0412\u0430\u0448 \u0432\u043E\u043F\u0440\u043E\u0441",
    duration: "\u0414\u043B\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0441\u0442\u044C (\u0441\u0435\u043A\u0443\u043D\u0434\u044B)",
    aspectRatio: "\u0421\u043E\u043E\u0442\u043D\u043E\u0448\u0435\u043D\u0438\u0435 \u0441\u0442\u043E\u0440\u043E\u043D",
    voice: "\u0413\u043E\u043B\u043E\u0441",
    attachImage: "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
    uploadImage: "\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
    // Placeholders
    enterQuestion: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0432\u0430\u0448 \u0432\u043E\u043F\u0440\u043E\u0441...",
    enterPrompt: "\u041E\u043F\u0438\u0448\u0438\u0442\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435, \u043A\u043E\u0442\u043E\u0440\u043E\u0435 \u0445\u043E\u0442\u0438\u0442\u0435 \u0441\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C...",
    enterToken: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u043E\u043A\u0435\u043D...",
    // Buttons
    send: "\u041E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C",
    saveChat: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0447\u0430\u0442",
    clear: "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C",
    ask: "\u0421\u043F\u0440\u043E\u0441\u0438\u0442\u044C",
    cancel: "\u041E\u0442\u043C\u0435\u043D\u0430",
    generate: "\u0413\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u0442\u044C",
    // Messages
    thinking: "\u0414\u0443\u043C\u0430\u044E...",
    noMessages: "\u041D\u0435\u0442 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0439 \u0434\u043B\u044F \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F",
    enterQuestionMsg: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441",
    enterPromptMsg: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043F\u0440\u043E\u043C\u043F\u0442",
    chatSaved: "\u0427\u0430\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D \u0432",
    saveError: "\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F",
    imageSaved: "\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E",
    imageError: "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
    videoSaved: "\u0412\u0438\u0434\u0435\u043E \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E",
    videoError: "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0432\u0438\u0434\u0435\u043E",
    audioSaved: "\u0410\u0443\u0434\u0438\u043E \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E",
    audioError: "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0441\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0430\u0443\u0434\u0438\u043E",
    generating: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F...",
    generatingVideo: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0432\u0438\u0434\u0435\u043E...",
    generatingAudio: "\u0413\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u044F \u0430\u0443\u0434\u0438\u043E...",
    answerSaved: "\u041E\u0442\u0432\u0435\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0443",
    unexpectedResponse: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D \u043D\u0435\u043E\u0436\u0438\u0434\u0430\u043D\u043D\u044B\u0439 \u043E\u0442\u0432\u0435\u0442 \u043E\u0442 API",
    error: "\u041E\u0448\u0438\u0431\u043A\u0430",
    imageUploaded: "\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435 \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E",
    // User/AI labels
    user: "\u0412\u044B",
    ai: "\u0418\u0418",
    // Settings
    settingsTitle: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Pollinations AI",
    defaultModel: "\u041C\u043E\u0434\u0435\u043B\u044C \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    defaultModelDesc: "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u043C\u043E\u0434\u0435\u043B\u044C \u0418\u0418 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    saveChatsToNotes: "\u0421\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C \u0447\u0430\u0442\u044B \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
    saveChatsDesc: "\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C \u0440\u0430\u0437\u0433\u043E\u0432\u043E\u0440\u044B \u0441 \u0418\u0418 \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0438",
    notesFolder: "\u041F\u0430\u043F\u043A\u0430 \u0434\u043B\u044F \u0437\u0430\u043C\u0435\u0442\u043E\u043A",
    notesFolderDesc: "\u041F\u0430\u043F\u043A\u0430, \u043A\u0443\u0434\u0430 \u0431\u0443\u0434\u0443\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C\u0441\u044F \u0447\u0430\u0442\u044B \u0441 \u0418\u0418",
    apiToken: "API \u0442\u043E\u043A\u0435\u043D",
    apiTokenDesc: "\u0422\u043E\u043A\u0435\u043D \u0434\u043B\u044F \u0434\u043E\u0441\u0442\u0443\u043F\u0430 \u043A API (\u043E\u043F\u0446\u0438\u043E\u043D\u0430\u043B\u044C\u043D\u043E)",
    imagesFolder: "\u041F\u0430\u043F\u043A\u0430 \u0434\u043B\u044F \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439",
    imagesFolderDesc: "\u041F\u0430\u043F\u043A\u0430, \u043A\u0443\u0434\u0430 \u0431\u0443\u0434\u0443\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C\u0441\u044F \u0441\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0435 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u044F",
    defaultImageModel: "\u041C\u043E\u0434\u0435\u043B\u044C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    defaultImageModelDesc: "\u041C\u043E\u0434\u0435\u043B\u044C \u0434\u043B\u044F \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438 \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0439 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    videosFolder: "\u041F\u0430\u043F\u043A\u0430 \u0434\u043B\u044F \u0432\u0438\u0434\u0435\u043E",
    videosFolderDesc: "\u041F\u0430\u043F\u043A\u0430, \u043A\u0443\u0434\u0430 \u0431\u0443\u0434\u0443\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C\u0441\u044F \u0441\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0435 \u0432\u0438\u0434\u0435\u043E",
    defaultVideoModel: "\u041C\u043E\u0434\u0435\u043B\u044C \u0432\u0438\u0434\u0435\u043E \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    defaultVideoModelDesc: "\u041C\u043E\u0434\u0435\u043B\u044C \u0434\u043B\u044F \u0433\u0435\u043D\u0435\u0440\u0430\u0446\u0438\u0438 \u0432\u0438\u0434\u0435\u043E \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    audioFolder: "\u041F\u0430\u043F\u043A\u0430 \u0434\u043B\u044F \u0430\u0443\u0434\u0438\u043E",
    audioFolderDesc: "\u041F\u0430\u043F\u043A\u0430, \u043A\u0443\u0434\u0430 \u0431\u0443\u0434\u0443\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C\u0441\u044F \u0441\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0435 \u0430\u0443\u0434\u0438\u043E",
    language: "\u042F\u0437\u044B\u043A",
    languageDesc: "\u042F\u0437\u044B\u043A \u0438\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441\u0430",
    showFreeModelsOnly: "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0442\u043E\u043B\u044C\u043A\u043E \u0431\u0435\u0441\u043F\u043B\u0430\u0442\u043D\u044B\u0435 \u043C\u043E\u0434\u0435\u043B\u0438",
    showFreeModelsOnlyDesc: "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0442\u043E\u043B\u044C\u043A\u043E \u043C\u043E\u0434\u0435\u043B\u0438, \u0440\u0430\u0431\u043E\u0442\u0430\u044E\u0449\u0438\u0435 \u0431\u0435\u0437 API \u043A\u043B\u044E\u0447\u0430",
    // Model categories
    categoryText: "\u0422\u0435\u043A\u0441\u0442",
    categoryImages: "\u041A\u0430\u0440\u0442\u0438\u043D\u043A\u0438",
    categoryVideo: "\u0412\u0438\u0434\u0435\u043E",
    categoryAudio: "\u0410\u0443\u0434\u0438\u043E",
    // Image models
    imageModelZimage: "Zimage (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E)",
    imageModelFlux: "Flux",
    imageModelTurbo: "Turbo (\u0431\u044B\u0441\u0442\u0440\u0430\u044F)",
    imageModelGPT: "GPT Image",
    imageModelKontext: "Kontext",
    imageModelSeeDream: "SeeDream",
    imageModelNanobanana: "Nanobanana"
  }
};
var PollinationsAIPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.models = [];
  }
  t(key) {
    return TRANSLATIONS[this.settings.language][key];
  }
  getCategoryForModel(modelName) {
    const name = modelName.toLowerCase();
    if (name === "veo" || name.includes("seedance")) {
      return this.t("categoryVideo");
    }
    if (name.includes("flux") || name === "turbo" || name === "gptimage" || name === "kontext" || name.includes("seedream") || name.includes("nanobanana") || name === "zimage") {
      return this.t("categoryImages");
    }
    if (name.includes("audio") || name.includes("tts") || name.includes("speech") || name.includes("midijourney")) {
      return this.t("categoryAudio");
    }
    return this.t("categoryText");
  }
  modelSupportsImages(modelName) {
    const model = this.models.find((m) => m.name === modelName);
    if (!model || !model.input_modalities) return false;
    return model.input_modalities.indexOf("image") !== -1 || model.input_modalities.indexOf("vision") !== -1;
  }
  modelSupportsImageInput(modelName) {
    const model = this.models.find((m) => m.name === modelName);
    if (!model || !model.input_modalities) return false;
    return model.input_modalities.includes("image");
  }
  isModelFree(modelName) {
    const name = modelName.toLowerCase();
    const freeModels = [
      // Text models (cheapest)
      "openai",
      "openai-fast",
      "qwen-coder",
      "mistral",
      "gemini-fast",
      "nova-micro",
      "deepseek",
      // Image models (basic free tier)
      "flux",
      "turbo",
      "gptimage",
      "kontext",
      "seedream",
      "nanobanana",
      "zimage"
    ];
    return freeModels.indexOf(name) !== -1;
  }
  async onload() {
    await this.loadSettings();
    this.currentModel = this.settings.defaultModel;
    void this.loadModels();
    this.addCommand({
      id: "open-ai-chat",
      name: this.t("openAIChat"),
      callback: () => {
        new AIchatModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "quick-ai-question",
      name: this.t("quickAIQuestion"),
      callback: () => {
        new QuickQuestionModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "generate-ai-image",
      name: this.t("generateAIImage"),
      callback: () => {
        new ImageGenerationModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "generate-ai-video",
      name: this.t("generateAIVideo"),
      callback: () => {
        new VideoGenerationModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "generate-ai-audio",
      name: this.t("generateAIAudio"),
      callback: () => {
        new AudioGenerationModal(this.app, this).open();
      }
    });
    this.addSettingTab(new PollinationsAISettingTab(this.app, this));
    this.addRibbonIcon("message-circle", this.t("aiChat"), (evt) => {
      new AIchatModal(this.app, this).open();
    });
  }
  async loadModels() {
    const defaultModels = [
      { name: "openai", description: "OpenAI GPT-5 Mini", input_modalities: ["text"] },
      { name: "mistral", description: "Mistral Small", input_modalities: ["text"] },
      { name: "gemini-fast", description: "Gemini Flash Lite", input_modalities: ["text"] },
      { name: "qwen-coder", description: "Qwen Coder", input_modalities: ["text"] },
      { name: "flux", description: "Flux Image Generator", input_modalities: ["text"] },
      { name: "turbo", description: "Turbo Image (Fast)", input_modalities: ["text"] }
    ];
    try {
      const headers = {};
      if (this.settings.apiToken) {
        headers["Authorization"] = `Bearer ${this.settings.apiToken}`;
      }
      const textResponse = await (0, import_obsidian.requestUrl)({
        url: "https://gen.pollinations.ai/text/models",
        method: "GET",
        headers,
        throw: false
      });
      const imageResponse = await (0, import_obsidian.requestUrl)({
        url: "https://gen.pollinations.ai/image/models",
        method: "GET",
        headers,
        throw: false
      });
      console.debug("Text models response:", textResponse);
      console.debug("Image models response:", imageResponse);
      const allModels = [];
      if (textResponse.status === 200 && textResponse.json && Array.isArray(textResponse.json)) {
        const textModels = textResponse.json.filter((m) => !m.is_specialized).map((model) => ({
          name: model.name,
          description: model.description || model.name,
          input_modalities: model.input_modalities || ["text"]
        }));
        allModels.push(...textModels);
      }
      if (imageResponse.status === 200 && imageResponse.json && Array.isArray(imageResponse.json)) {
        const imageModels = imageResponse.json.filter((m) => !m.is_specialized).map((model) => ({
          name: model.name,
          description: model.description || model.name,
          input_modalities: model.input_modalities || ["text"]
        }));
        allModels.push(...imageModels);
      }
      if (allModels.length > 0) {
        this.models = allModels;
        console.debug("Loaded models:", this.models);
        return;
      }
      console.warn("API response not valid, using default models");
      this.models = defaultModels;
    } catch (error) {
      console.warn("\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044C \u043C\u043E\u0434\u0435\u043B\u0438 \u0438\u0437 API, \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0435\u043C \u0441\u043F\u0438\u0441\u043E\u043A \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E:", error);
      this.models = defaultModels;
    }
  }
  async communicateWithAI(modelName, messages) {
    try {
      const headers = {
        "Content-Type": "application/json"
      };
      if (this.settings.apiToken) {
        headers["Authorization"] = `Bearer ${this.settings.apiToken}`;
      }
      const requestBody = {
        model: modelName,
        messages,
        private: true
      };
      console.debug("Pollinations API \u0437\u0430\u043F\u0440\u043E\u0441:", {
        url: "https://gen.pollinations.ai/v1/chat/completions",
        model: modelName,
        messages
      });
      const response = await (0, import_obsidian.requestUrl)({
        url: "https://gen.pollinations.ai/v1/chat/completions",
        method: "POST",
        headers,
        body: JSON.stringify(requestBody),
        throw: false
      });
      if (response.status === 200 && response.json) {
        return response.json;
      } else {
        return { error: `HTTP ${response.status}` };
      }
    } catch (error) {
      return { error: error.toString() };
    }
  }
  async saveConversationToNote(conversation, title) {
    if (!this.settings.saveToNotes) return;
    const folderPath = this.settings.notesFolder;
    if (!this.app.vault.getAbstractFileByPath(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 19).replace(/:/g, "-");
    const fileName = `${title || "\u0418\u0418 \u0447\u0430\u0442"} ${timestamp}.md`;
    const filePath = `${folderPath}/${fileName}`;
    let content = `# ${title || "\u0418\u0418 \u0447\u0430\u0442"}

`;
    content += `**\u041C\u043E\u0434\u0435\u043B\u044C:** ${this.currentModel}
`;
    content += `**\u0414\u0430\u0442\u0430:** ${(/* @__PURE__ */ new Date()).toLocaleString("ru-RU")}

`;
    content += `---

`;
    conversation.forEach((message, index) => {
      const roleIcon = message.role === "user" ? "\u{1F464}" : "\u{1F916}";
      const roleText = message.role === "user" ? "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C" : "\u0418\u0418";
      content += `## ${roleIcon} ${roleText}

`;
      content += `${message.content}

`;
      if (index < conversation.length - 1) {
        content += `---

`;
      }
    });
    try {
      await this.app.vault.create(filePath, content);
      new import_obsidian.Notice(`${this.t("chatSaved")} ${filePath}`);
    } catch (error) {
      new import_obsidian.Notice(`${this.t("saveError")}: ${error}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async generateImage(prompt, model = "zimage", width = 1024, height = 1024, referenceImage) {
    try {
      if (!this.settings.apiToken) {
        return { error: "API key required for image generation. Please add it in settings." };
      }
      const url = new URL(`https://gen.pollinations.ai/image/${encodeURIComponent(prompt)}`);
      url.searchParams.set("model", model);
      url.searchParams.set("width", width.toString());
      url.searchParams.set("height", height.toString());
      url.searchParams.set("nologo", "true");
      url.searchParams.set("private", "true");
      url.searchParams.set("key", this.settings.apiToken);
      if (referenceImage && this.modelSupportsImageInput(model)) {
        if (referenceImage.startsWith("http://") || referenceImage.startsWith("https://")) {
          url.searchParams.set("image", referenceImage);
          console.log("Image-to-image with URL:", referenceImage.substring(0, 100));
        } else if (referenceImage.startsWith("data:")) {
          return {
            error: "Local files cannot be used for image editing. Please use a public image URL (http:// or https://) instead."
          };
        }
      }
      console.log("Generating image...");
      const response = await (0, import_obsidian.requestUrl)({
        url: url.toString(),
        method: "GET",
        throw: false
      });
      console.log("Image generation response:", { status: response.status, hasArrayBuffer: !!response.arrayBuffer });
      if (response.status === 200 && response.arrayBuffer) {
        const timestamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 19).replace(/:/g, "-");
        const filename = `ai-image-${timestamp}.png`;
        return {
          imageData: response.arrayBuffer,
          filename
        };
      } else {
        const errorText = response.text || response.json ? JSON.stringify(response.json) : "Unknown error";
        return { error: `HTTP ${response.status}: ${errorText}` };
      }
    } catch (error) {
      return { error: error.toString() };
    }
  }
  async saveImage(imageData, filename) {
    try {
      const folderPath = this.settings.imagesFolder;
      if (!this.app.vault.getAbstractFileByPath(folderPath)) {
        await this.app.vault.createFolder(folderPath);
      }
      const filePath = `${folderPath}/${filename}`;
      await this.app.vault.createBinary(filePath, imageData);
      return filePath;
    } catch (error) {
      console.error("Error saving image:", error);
      return null;
    }
  }
  async generateVideo(prompt, model = "veo", duration = 4, aspectRatio = "16:9", referenceImage) {
    try {
      if (!this.settings.apiToken) {
        return { error: "API key required for video generation. Please add it in settings." };
      }
      const url = new URL(`https://gen.pollinations.ai/image/${encodeURIComponent(prompt)}`);
      url.searchParams.set("model", model);
      url.searchParams.set("duration", duration.toString());
      url.searchParams.set("aspectRatio", aspectRatio);
      url.searchParams.set("nologo", "true");
      url.searchParams.set("private", "true");
      url.searchParams.set("key", this.settings.apiToken);
      if (referenceImage) {
        url.searchParams.set("image", referenceImage);
      }
      const response = await (0, import_obsidian.requestUrl)({
        url: url.toString(),
        method: "GET",
        throw: false
      });
      if (response.status === 200 && response.arrayBuffer) {
        const timestamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 19).replace(/:/g, "-");
        const filename = `ai-video-${timestamp}.mp4`;
        return {
          videoData: response.arrayBuffer,
          filename
        };
      } else {
        const errorText = response.text || response.json ? JSON.stringify(response.json) : "Unknown error";
        return { error: `HTTP ${response.status}: ${errorText}` };
      }
    } catch (error) {
      return { error: error.toString() };
    }
  }
  async saveVideo(videoData, filename) {
    try {
      const folderPath = this.settings.videosFolder;
      if (!this.app.vault.getAbstractFileByPath(folderPath)) {
        await this.app.vault.createFolder(folderPath);
      }
      const filePath = `${folderPath}/${filename}`;
      await this.app.vault.createBinary(filePath, videoData);
      return filePath;
    } catch (error) {
      console.error("Error saving video:", error);
      return null;
    }
  }
  async generateAudio(text, voice = "alloy") {
    var _a, _b, _c, _d;
    try {
      if (!this.settings.apiToken) {
        return { error: "API key required for audio generation. Please add it in settings." };
      }
      const headers = {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.apiToken}`
      };
      const requestBody = {
        model: "openai",
        messages: [{ role: "user", content: text }],
        modalities: ["audio"],
        audio: {
          voice,
          format: "wav"
        }
      };
      const response = await (0, import_obsidian.requestUrl)({
        url: "https://gen.pollinations.ai/v1/chat/completions",
        method: "POST",
        headers,
        body: JSON.stringify(requestBody),
        throw: false
      });
      if (response.status === 200 && response.json) {
        const audioData = (_d = (_c = (_b = (_a = response.json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.audio) == null ? void 0 : _d.data;
        if (audioData) {
          const binaryString = atob(audioData);
          const bytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }
          const timestamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 19).replace(/:/g, "-");
          const filename = `ai-audio-${timestamp}.wav`;
          return {
            audioData: bytes.buffer,
            filename
          };
        } else {
          return { error: "No audio data in response" };
        }
      } else {
        const errorText = response.text || response.json ? JSON.stringify(response.json) : "Unknown error";
        return { error: `HTTP ${response.status}: ${errorText}` };
      }
    } catch (error) {
      return { error: error.toString() };
    }
  }
  async saveAudio(audioData, filename) {
    try {
      const folderPath = this.settings.audioFolder;
      if (!this.app.vault.getAbstractFileByPath(folderPath)) {
        await this.app.vault.createFolder(folderPath);
      }
      const filePath = `${folderPath}/${filename}`;
      await this.app.vault.createBinary(filePath, audioData);
      return filePath;
    } catch (error) {
      console.error("Error saving audio:", error);
      return null;
    }
  }
};
var AIchatModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.conversation = [];
    this.attachedImageUrl = null;
    this.attachedImageEl = null;
    this.promptHistory = [];
    this.historyIndex = -1;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.t("aiChatTitle") });
    const modelContainer = contentEl.createDiv("model-selector");
    modelContainer.createEl("label", { text: this.plugin.t("model") + ":" });
    this.modelSelect = new import_obsidian.DropdownComponent(modelContainer);
    const modelsToShow = this.plugin.settings.showFreeModelsOnly ? this.plugin.models.filter((m) => this.plugin.isModelFree(m.name)) : this.plugin.models;
    const categories = /* @__PURE__ */ new Map();
    modelsToShow.forEach((model) => {
      const category = this.plugin.getCategoryForModel(model.name);
      if (!categories.has(category)) {
        categories.set(category, []);
      }
      const categoryModels = categories.get(category);
      if (categoryModels) {
        categoryModels.push(model);
      }
    });
    categories.forEach((models, category) => {
      models.forEach((model) => {
        this.modelSelect.addOption(model.name, `[${category}] ${model.description}`);
      });
    });
    this.modelSelect.setValue(this.plugin.currentModel);
    this.modelSelect.onChange((value) => {
      this.plugin.currentModel = value;
    });
    this.chatContainer = contentEl.createDiv("chat-container");
    const inputContainer = contentEl.createDiv("input-container");
    this.inputElement = new import_obsidian.TextComponent(inputContainer);
    this.inputElement.inputEl.placeholder = this.plugin.t("enterQuestion");
    this.inputElement.inputEl.addClass("input-wide");
    this.inputElement.inputEl.addClass("chat-input-multiline");
    this.inputElement.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.sendMessage();
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        this.navigateHistory("up");
      } else if (e.key === "ArrowDown") {
        e.preventDefault();
        this.navigateHistory("down");
      }
    });
    const sendButton = new import_obsidian.ButtonComponent(inputContainer);
    sendButton.setButtonText(this.plugin.t("send"));
    sendButton.onClick(() => void this.sendMessage());
    const buttonContainer = contentEl.createDiv("button-container");
    const saveButton = new import_obsidian.ButtonComponent(buttonContainer);
    saveButton.setButtonText(this.plugin.t("saveChat"));
    saveButton.onClick(() => void this.saveChat());
    const clearButton = new import_obsidian.ButtonComponent(buttonContainer);
    clearButton.setButtonText(this.plugin.t("clear"));
    clearButton.onClick(() => this.clearChat());
  }
  async sendMessage() {
    const message = this.inputElement.getValue().trim();
    if (!message) return;
    this.promptHistory.push(message);
    this.historyIndex = this.promptHistory.length;
    this.addMessage("user", message);
    this.inputElement.setValue("");
    const category = this.plugin.getCategoryForModel(this.plugin.currentModel);
    const isImageModel = category === this.plugin.t("categoryImages");
    const isVideoModel = category === this.plugin.t("categoryVideo");
    const loadingEl = this.chatContainer.createDiv("loading-message");
    loadingEl.textContent = "\u{1F916} " + this.plugin.t("thinking");
    try {
      if (isVideoModel) {
        const result = await this.plugin.generateVideo(message, this.plugin.currentModel, 4, "16:9");
        loadingEl.remove();
        if (result.error) {
          this.addMessage("assistant", `${this.plugin.t("error")}: ${result.error}`);
        } else if (result.videoData && result.filename) {
          const filePath = await this.plugin.saveVideo(result.videoData, result.filename);
          if (filePath) {
            this.addMessage("assistant", `${this.plugin.t("videoSaved")}: [[${filePath}]]`);
          } else {
            this.addMessage("assistant", this.plugin.t("videoError"));
          }
        }
      } else if (isImageModel) {
        const result = await this.plugin.generateImage(
          message,
          this.plugin.currentModel,
          1024,
          1024
        );
        loadingEl.remove();
        if (result.error) {
          this.addMessage("assistant", `${this.plugin.t("error")}: ${result.error}`);
        } else if (result.imageData && result.filename) {
          const filePath = await this.plugin.saveImage(result.imageData, result.filename);
          if (filePath) {
            this.addMessage("assistant", `${this.plugin.t("imageSaved")}: [[${filePath}]]`);
          } else {
            this.addMessage("assistant", this.plugin.t("imageError"));
          }
        }
      } else {
        const messages = this.conversation.map((msg) => ({
          role: msg.role,
          content: msg.content
        }));
        const response = await this.plugin.communicateWithAI(this.plugin.currentModel, messages);
        loadingEl.remove();
        if (response.error) {
          this.addMessage("assistant", `${this.plugin.t("error")}: ${response.error}`);
        } else if (response.choices && response.choices[0] && response.choices[0].message) {
          this.addMessage("assistant", response.choices[0].message.content);
        } else {
          this.addMessage("assistant", this.plugin.t("unexpectedResponse"));
        }
      }
    } catch (error) {
      loadingEl.remove();
      this.addMessage("assistant", `${this.plugin.t("error")}: ${error}`);
    }
  }
  navigateHistory(direction) {
    if (this.promptHistory.length === 0) return;
    if (direction === "up") {
      if (this.historyIndex > 0) {
        this.historyIndex--;
        this.inputElement.setValue(this.promptHistory[this.historyIndex]);
      }
    } else {
      if (this.historyIndex < this.promptHistory.length - 1) {
        this.historyIndex++;
        this.inputElement.setValue(this.promptHistory[this.historyIndex]);
      } else {
        this.historyIndex = this.promptHistory.length;
        this.inputElement.setValue("");
      }
    }
  }
  addMessage(role, content) {
    const message = {
      role,
      content,
      timestamp: /* @__PURE__ */ new Date()
    };
    this.conversation.push(message);
    const messageEl = this.chatContainer.createDiv("chat-message");
    messageEl.addClass(role === "user" ? "user-message" : "assistant-message");
    const roleIcon = role === "user" ? "\u{1F464}" : "\u{1F916}";
    const roleText = role === "user" ? this.plugin.t("user") : this.plugin.t("ai");
    const headerDiv = messageEl.createDiv("message-header");
    const headerStrong = headerDiv.createEl("strong");
    headerStrong.textContent = `${roleIcon} ${roleText}`;
    const headerSmall = headerDiv.createEl("small");
    headerSmall.textContent = message.timestamp.toLocaleTimeString("ru-RU");
    const contentDiv = messageEl.createDiv("message-content");
    contentDiv.textContent = content;
  }
  async saveChat() {
    if (this.conversation.length === 0) {
      new import_obsidian.Notice(this.plugin.t("noMessages"));
      return;
    }
    const title = `\u0427\u0430\u0442 \u0441 ${this.plugin.currentModel}`;
    await this.plugin.saveConversationToNote(this.conversation, title);
  }
  clearChat() {
    this.conversation = [];
    this.chatContainer.empty();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var QuickQuestionModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.t("quickQuestionTitle") });
    const modelContainer = contentEl.createDiv();
    modelContainer.createEl("label", { text: this.plugin.t("model") + ":" });
    this.modelSelect = new import_obsidian.DropdownComponent(modelContainer);
    const modelsToShow = this.plugin.settings.showFreeModelsOnly ? this.plugin.models.filter((m) => this.plugin.isModelFree(m.name)) : this.plugin.models;
    const categories = /* @__PURE__ */ new Map();
    modelsToShow.forEach((model) => {
      const category = this.plugin.getCategoryForModel(model.name);
      if (!categories.has(category)) {
        categories.set(category, []);
      }
      const categoryModels = categories.get(category);
      if (categoryModels) {
        categoryModels.push(model);
      }
    });
    categories.forEach((models, category) => {
      models.forEach((model) => {
        this.modelSelect.addOption(model.name, `[${category}] ${model.description}`);
      });
    });
    const inputContainer = contentEl.createDiv();
    inputContainer.createEl("label", { text: this.plugin.t("yourQuestion") + ":" });
    this.inputElement = new import_obsidian.TextComponent(inputContainer);
    this.inputElement.inputEl.placeholder = this.plugin.t("enterQuestion");
    this.inputElement.inputEl.addClass("input-full");
    this.inputElement.inputEl.addClass("input-tall");
    const buttonContainer = contentEl.createDiv();
    const askButton = new import_obsidian.ButtonComponent(buttonContainer);
    askButton.setButtonText(this.plugin.t("ask"));
    askButton.setCta();
    askButton.onClick(() => this.askQuestion());
    const cancelButton = new import_obsidian.ButtonComponent(buttonContainer);
    cancelButton.setButtonText(this.plugin.t("cancel"));
    cancelButton.onClick(() => this.close());
  }
  async askQuestion() {
    const question = this.inputElement.getValue().trim();
    if (!question) {
      new import_obsidian.Notice(this.plugin.t("enterQuestionMsg"));
      return;
    }
    const selectedModel = this.modelSelect.getValue();
    try {
      const messages = [{ role: "user", content: question }];
      const response = await this.plugin.communicateWithAI(selectedModel, messages);
      if (response.error) {
        new import_obsidian.Notice(`${this.plugin.t("error")}: ${response.error}`);
        return;
      }
      if (response.choices && response.choices[0] && response.choices[0].message) {
        const answer = response.choices[0].message.content;
        const conversation = [
          { role: "user", content: question, timestamp: /* @__PURE__ */ new Date() },
          { role: "assistant", content: answer, timestamp: /* @__PURE__ */ new Date() }
        ];
        await this.plugin.saveConversationToNote(conversation, "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u043E\u043F\u0440\u043E\u0441");
        new import_obsidian.Notice(this.plugin.t("answerSaved"));
        this.close();
      } else {
        new import_obsidian.Notice(this.plugin.t("unexpectedResponse"));
      }
    } catch (error) {
      new import_obsidian.Notice(`${this.plugin.t("error")}: ${error}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ImageGenerationModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  updateModelList() {
    this.modelSelect.selectEl.empty();
    const imageModels = this.plugin.models.filter((m) => {
      const category = this.plugin.getCategoryForModel(m.name);
      return category === this.plugin.t("categoryImages");
    });
    imageModels.forEach((model) => {
      this.modelSelect.addOption(model.name, model.description);
    });
    if (imageModels.length === 0) {
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.t("imageGenerationTitle") });
    const modelContainer = contentEl.createDiv();
    modelContainer.createEl("label", { text: this.plugin.t("model") + ":" });
    this.modelSelect = new import_obsidian.DropdownComponent(modelContainer);
    this.updateModelList();
    this.modelSelect.setValue(this.plugin.settings.defaultImageModel);
    const promptContainer = contentEl.createDiv();
    promptContainer.createEl("label", { text: this.plugin.t("prompt") + ":" });
    this.promptInput = new import_obsidian.TextComponent(promptContainer);
    this.promptInput.inputEl.placeholder = this.plugin.t("enterPrompt");
    this.promptInput.inputEl.addClass("input-full");
    this.promptInput.inputEl.addClass("input-tall");
    const sizeContainer = contentEl.createDiv();
    sizeContainer.createEl("label", { text: this.plugin.t("size") + ":" });
    const sizeInputContainer = sizeContainer.createDiv("size-input-container");
    this.widthInput = new import_obsidian.TextComponent(sizeInputContainer);
    this.widthInput.setValue("1024");
    this.widthInput.inputEl.addClass("dimension-input");
    sizeInputContainer.createSpan({ text: "\xD7" });
    this.heightInput = new import_obsidian.TextComponent(sizeInputContainer);
    this.heightInput.setValue("1024");
    this.heightInput.inputEl.addClass("dimension-input");
    const buttonContainer = contentEl.createDiv();
    const generateButton = new import_obsidian.ButtonComponent(buttonContainer);
    generateButton.setButtonText(this.plugin.t("generate"));
    generateButton.setCta();
    generateButton.onClick(() => this.generateImage());
    const cancelButton = new import_obsidian.ButtonComponent(buttonContainer);
    cancelButton.setButtonText(this.plugin.t("cancel"));
    cancelButton.onClick(() => this.close());
  }
  async generateImage() {
    var _a;
    const prompt = this.promptInput.getValue().trim();
    if (!prompt) {
      new import_obsidian.Notice(this.plugin.t("enterPromptMsg"));
      return;
    }
    const model = this.modelSelect.getValue();
    const width = parseInt(this.widthInput.getValue()) || 1024;
    const height = parseInt(this.heightInput.getValue()) || 1024;
    const loadingNotice = new import_obsidian.Notice(this.plugin.t("generating"), 0);
    try {
      const result = await this.plugin.generateImage(prompt, model, width, height);
      loadingNotice.hide();
      if (result.error) {
        new import_obsidian.Notice(`${this.plugin.t("error")}: ${result.error}`);
        return;
      }
      if (result.imageData && result.filename) {
        const filePath = await this.plugin.saveImage(result.imageData, result.filename);
        if (filePath) {
          new import_obsidian.Notice(`${this.plugin.t("imageSaved")}: ${filePath}`);
          const activeFile = this.app.workspace.getActiveFile();
          if (activeFile) {
            const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
            if (editor) {
              editor.replaceSelection(`![[${filePath}]]
`);
            }
          }
          this.close();
        } else {
          new import_obsidian.Notice(this.plugin.t("imageError"));
        }
      }
    } catch (error) {
      loadingNotice.hide();
      new import_obsidian.Notice(`${this.plugin.t("error")}: ${error}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var VideoGenerationModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.t("videoGenerationTitle") });
    const videoModels = [
      { id: "veo", name: "Veo (4-8s, text-to-video)" },
      { id: "seedance", name: "Seedance (2-10s, text/image-to-video)" },
      { id: "seedance-pro", name: "Seedance Pro" }
    ];
    const modelContainer = contentEl.createDiv();
    modelContainer.createEl("label", { text: this.plugin.t("model") + ":" });
    this.modelSelect = new import_obsidian.DropdownComponent(modelContainer);
    videoModels.forEach((model) => {
      this.modelSelect.addOption(model.id, model.name);
    });
    this.modelSelect.setValue(this.plugin.settings.defaultVideoModel);
    const promptContainer = contentEl.createDiv();
    promptContainer.createEl("label", { text: this.plugin.t("prompt") + ":" });
    this.promptInput = new import_obsidian.TextComponent(promptContainer);
    this.promptInput.inputEl.placeholder = this.plugin.t("enterPrompt");
    this.promptInput.inputEl.addClass("input-full");
    this.promptInput.inputEl.addClass("input-tall");
    const durationContainer = contentEl.createDiv();
    durationContainer.createEl("label", { text: this.plugin.t("duration") + ":" });
    this.durationInput = new import_obsidian.TextComponent(durationContainer);
    this.durationInput.setValue("4");
    this.durationInput.inputEl.addClass("duration-input");
    const aspectContainer = contentEl.createDiv();
    aspectContainer.createEl("label", { text: this.plugin.t("aspectRatio") + ":" });
    this.aspectRatioSelect = new import_obsidian.DropdownComponent(aspectContainer);
    this.aspectRatioSelect.addOption("16:9", "16:9 (Landscape)");
    this.aspectRatioSelect.addOption("9:16", "9:16 (Portrait)");
    this.aspectRatioSelect.setValue("16:9");
    const buttonContainer = contentEl.createDiv();
    const generateButton = new import_obsidian.ButtonComponent(buttonContainer);
    generateButton.setButtonText(this.plugin.t("generate"));
    generateButton.setCta();
    generateButton.onClick(() => this.generateVideo());
    const cancelButton = new import_obsidian.ButtonComponent(buttonContainer);
    cancelButton.setButtonText(this.plugin.t("cancel"));
    cancelButton.onClick(() => this.close());
  }
  async generateVideo() {
    var _a;
    const prompt = this.promptInput.getValue().trim();
    if (!prompt) {
      new import_obsidian.Notice(this.plugin.t("enterPromptMsg"));
      return;
    }
    const model = this.modelSelect.getValue();
    const duration = parseInt(this.durationInput.getValue()) || 4;
    const aspectRatio = this.aspectRatioSelect.getValue();
    const loadingNotice = new import_obsidian.Notice(this.plugin.t("generatingVideo"), 0);
    try {
      const result = await this.plugin.generateVideo(prompt, model, duration, aspectRatio);
      loadingNotice.hide();
      if (result.error) {
        new import_obsidian.Notice(`${this.plugin.t("error")}: ${result.error}`);
        return;
      }
      if (result.videoData && result.filename) {
        const filePath = await this.plugin.saveVideo(result.videoData, result.filename);
        if (filePath) {
          new import_obsidian.Notice(`${this.plugin.t("videoSaved")}: ${filePath}`);
          const activeFile = this.app.workspace.getActiveFile();
          if (activeFile) {
            const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
            if (editor) {
              editor.replaceSelection(`![[${filePath}]]
`);
            }
          }
          this.close();
        } else {
          new import_obsidian.Notice(this.plugin.t("videoError"));
        }
      }
    } catch (error) {
      loadingNotice.hide();
      new import_obsidian.Notice(`${this.plugin.t("error")}: ${error}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AudioGenerationModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.plugin.t("audioGenerationTitle") });
    const textContainer = contentEl.createDiv();
    textContainer.createEl("label", { text: this.plugin.t("prompt") + ":" });
    this.textInput = new import_obsidian.TextComponent(textContainer);
    this.textInput.inputEl.placeholder = this.plugin.t("enterPrompt");
    this.textInput.inputEl.addClass("input-full");
    this.textInput.inputEl.addClass("input-tall");
    const voiceContainer = contentEl.createDiv();
    voiceContainer.createEl("label", { text: this.plugin.t("voice") + ":" });
    this.voiceSelect = new import_obsidian.DropdownComponent(voiceContainer);
    const voices = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"];
    voices.forEach((voice) => {
      this.voiceSelect.addOption(voice, voice.charAt(0).toUpperCase() + voice.slice(1));
    });
    this.voiceSelect.setValue("alloy");
    const buttonContainer = contentEl.createDiv();
    const generateButton = new import_obsidian.ButtonComponent(buttonContainer);
    generateButton.setButtonText(this.plugin.t("generate"));
    generateButton.setCta();
    generateButton.onClick(() => this.generateAudio());
    const cancelButton = new import_obsidian.ButtonComponent(buttonContainer);
    cancelButton.setButtonText(this.plugin.t("cancel"));
    cancelButton.onClick(() => this.close());
  }
  async generateAudio() {
    var _a;
    const text = this.textInput.getValue().trim();
    if (!text) {
      new import_obsidian.Notice(this.plugin.t("enterPromptMsg"));
      return;
    }
    const voice = this.voiceSelect.getValue();
    const loadingNotice = new import_obsidian.Notice(this.plugin.t("generatingAudio"), 0);
    try {
      const result = await this.plugin.generateAudio(text, voice);
      loadingNotice.hide();
      if (result.error) {
        new import_obsidian.Notice(`${this.plugin.t("error")}: ${result.error}`);
        return;
      }
      if (result.audioData && result.filename) {
        const filePath = await this.plugin.saveAudio(result.audioData, result.filename);
        if (filePath) {
          new import_obsidian.Notice(`${this.plugin.t("audioSaved")}: ${filePath}`);
          const activeFile = this.app.workspace.getActiveFile();
          if (activeFile) {
            const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
            if (editor) {
              editor.replaceSelection(`![[${filePath}]]
`);
            }
          }
          this.close();
        } else {
          new import_obsidian.Notice(this.plugin.t("audioError"));
        }
      }
    } catch (error) {
      loadingNotice.hide();
      new import_obsidian.Notice(`${this.plugin.t("error")}: ${error}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var PollinationsAISettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("settingsTitle")).setHeading();
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("language")).setDesc(this.plugin.t("languageDesc")).addDropdown((dropdown) => {
      dropdown.addOption("en", "English");
      dropdown.addOption("ru", "\u0420\u0443\u0441\u0441\u043A\u0438\u0439");
      dropdown.setValue(this.plugin.settings.language);
      dropdown.onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("showFreeModelsOnly")).setDesc(this.plugin.t("showFreeModelsOnlyDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showFreeModelsOnly).onChange(async (value) => {
      this.plugin.settings.showFreeModelsOnly = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("defaultModel")).setDesc(this.plugin.t("defaultModelDesc")).addDropdown((dropdown) => {
      const modelsToShow = this.plugin.settings.showFreeModelsOnly ? this.plugin.models.filter((m) => this.plugin.isModelFree(m.name)) : this.plugin.models;
      const categories = /* @__PURE__ */ new Map();
      modelsToShow.forEach((model) => {
        const category = this.plugin.getCategoryForModel(model.name);
        if (!categories.has(category)) {
          categories.set(category, []);
        }
        const categoryModels = categories.get(category);
        if (categoryModels) {
          categoryModels.push(model);
        }
      });
      categories.forEach((models, category) => {
        models.forEach((model) => {
          dropdown.addOption(model.name, `[${category}] ${model.description}`);
        });
      });
      dropdown.setValue(this.plugin.settings.defaultModel);
      dropdown.onChange(async (value) => {
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("saveChatsToNotes")).setDesc(this.plugin.t("saveChatsDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.saveToNotes).onChange(async (value) => {
      this.plugin.settings.saveToNotes = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("notesFolder")).setDesc(this.plugin.t("notesFolderDesc")).addText((text) => text.setPlaceholder("AI chats").setValue(this.plugin.settings.notesFolder).onChange(async (value) => {
      this.plugin.settings.notesFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("apiToken")).setDesc(this.plugin.t("apiTokenDesc")).addText((text) => text.setPlaceholder(this.plugin.t("enterToken")).setValue(this.plugin.settings.apiToken).onChange(async (value) => {
      this.plugin.settings.apiToken = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("imagesFolder")).setDesc(this.plugin.t("imagesFolderDesc")).addText((text) => text.setPlaceholder("AI images").setValue(this.plugin.settings.imagesFolder).onChange(async (value) => {
      this.plugin.settings.imagesFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("defaultImageModel")).setDesc(this.plugin.t("defaultImageModelDesc")).addDropdown((dropdown) => {
      dropdown.addOption("zimage", this.plugin.t("imageModelZimage"));
      dropdown.addOption("flux", this.plugin.t("imageModelFlux"));
      dropdown.addOption("turbo", this.plugin.t("imageModelTurbo"));
      dropdown.addOption("gptimage", this.plugin.t("imageModelGPT"));
      dropdown.addOption("kontext", this.plugin.t("imageModelKontext"));
      dropdown.addOption("seedream", this.plugin.t("imageModelSeeDream"));
      dropdown.addOption("nanobanana", this.plugin.t("imageModelNanobanana"));
      dropdown.setValue(this.plugin.settings.defaultImageModel);
      dropdown.onChange(async (value) => {
        this.plugin.settings.defaultImageModel = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("videosFolder")).setDesc(this.plugin.t("videosFolderDesc")).addText((text) => text.setPlaceholder("AI videos").setValue(this.plugin.settings.videosFolder).onChange(async (value) => {
      this.plugin.settings.videosFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("defaultVideoModel")).setDesc(this.plugin.t("defaultVideoModelDesc")).addDropdown((dropdown) => {
      dropdown.addOption("veo", "Veo");
      dropdown.addOption("seedance", "Seedance");
      dropdown.addOption("seedance-pro", "Seedance Pro");
      dropdown.setValue(this.plugin.settings.defaultVideoModel);
      dropdown.onChange(async (value) => {
        this.plugin.settings.defaultVideoModel = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName(this.plugin.t("audioFolder")).setDesc(this.plugin.t("audioFolderDesc")).addText((text) => text.setPlaceholder("AI audio").setValue(this.plugin.settings.audioFolder).onChange(async (value) => {
      this.plugin.settings.audioFolder = value;
      await this.plugin.saveSettings();
    }));
  }
};
