/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PollinationsAIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultModel: "openai",
  saveToNotes: true,
  notesFolder: "\u0427\u0430\u0442\u044B \u0441 \u0418\u0418",
  apiToken: ""
};
var PollinationsAIPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.models = [];
  }
  async onload() {
    await this.loadSettings();
    this.currentModel = this.settings.defaultModel;
    await this.loadModels();
    this.addCommand({
      id: "open-ai-chat",
      name: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0418\u0418 \u0447\u0430\u0442",
      callback: () => {
        new AIchatModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "quick-ai-question",
      name: "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u043E\u043F\u0440\u043E\u0441 \u0418\u0418",
      callback: () => {
        new QuickQuestionModal(this.app, this).open();
      }
    });
    this.addSettingTab(new PollinationsAISettingTab(this.app, this));
    this.addRibbonIcon("message-circle", "\u0418\u0418 \u0427\u0430\u0442", (evt) => {
      new AIchatModal(this.app, this).open();
    });
  }
  async loadModels() {
    try {
      const response = await fetch("https://text.pollinations.ai/models");
      if (response.ok) {
        const models = await response.json();
        this.models = models.map((model) => {
          let input_modalities = model.input_modalities || [];
          if (!input_modalities.length) {
            if (model.name.toLowerCase().includes("openai")) {
              input_modalities = ["text", "image"];
            } else if (model.name.toLowerCase().includes("audio")) {
              input_modalities = ["text", "audio"];
            } else {
              input_modalities = ["text"];
            }
          }
          return {
            name: model.name,
            description: model.description || "\u0411\u0435\u0437 \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u044F",
            input_modalities
          };
        });
      } else {
        this.models = [{
          name: "openai",
          description: "OpenAI GPT-4o Mini",
          input_modalities: ["text"]
        }];
      }
    } catch (error) {
      console.error("\u041E\u0448\u0438\u0431\u043A\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043A\u0438 \u043C\u043E\u0434\u0435\u043B\u0435\u0439:", error);
      this.models = [{
        name: "openai",
        description: "OpenAI GPT-4o Mini",
        input_modalities: ["text"]
      }];
    }
  }
  async communicateWithAI(modelName, messages) {
    try {
      const lastUserMessage = messages.filter((msg) => msg.role === "user").pop();
      if (!lastUserMessage) {
        return { error: "\u041D\u0435\u0442 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u044F \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F" };
      }
      const encodedPrompt = `'${lastUserMessage.content}'`;
      const url = new URL(`https://text.pollinations.ai/${encodedPrompt}`);
      url.searchParams.set("model", modelName);
      url.searchParams.set("private", "true");
      console.log("Pollinations API \u0437\u0430\u043F\u0440\u043E\u0441:", {
        url: url.toString(),
        model: modelName,
        prompt: lastUserMessage.content
      });
      const response = await fetch(url.toString(), {
        method: "GET"
      });
      if (response.ok) {
        const text = await response.text();
        return {
          choices: [{
            message: {
              content: text
            }
          }]
        };
      } else {
        return { error: `HTTP ${response.status}: ${response.statusText}` };
      }
    } catch (error) {
      return { error: error.toString() };
    }
  }
  async saveConversationToNote(conversation, title) {
    if (!this.settings.saveToNotes)
      return;
    const folderPath = this.settings.notesFolder;
    if (!this.app.vault.getAbstractFileByPath(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
    const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-");
    const fileName = `${title || "\u0418\u0418 \u0447\u0430\u0442"} ${timestamp}.md`;
    const filePath = `${folderPath}/${fileName}`;
    let content = `# ${title || "\u0418\u0418 \u0447\u0430\u0442"}

`;
    content += `**\u041C\u043E\u0434\u0435\u043B\u044C:** ${this.currentModel}
`;
    content += `**\u0414\u0430\u0442\u0430:** ${new Date().toLocaleString("ru-RU")}

`;
    content += `---

`;
    conversation.forEach((message, index) => {
      const roleIcon = message.role === "user" ? "\u{1F464}" : "\u{1F916}";
      const roleText = message.role === "user" ? "\u041F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C" : "\u0418\u0418";
      content += `## ${roleIcon} ${roleText}

`;
      content += `${message.content}

`;
      if (index < conversation.length - 1) {
        content += `---

`;
      }
    });
    try {
      await this.app.vault.create(filePath, content);
      new import_obsidian.Notice(`\u0427\u0430\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D \u0432: ${filePath}`);
    } catch (error) {
      new import_obsidian.Notice(`\u041E\u0448\u0438\u0431\u043A\u0430 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F: ${error}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var AIchatModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.conversation = [];
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u0418\u0418 \u0427\u0430\u0442" });
    const modelContainer = contentEl.createDiv("model-selector");
    modelContainer.createEl("label", { text: "\u041C\u043E\u0434\u0435\u043B\u044C: " });
    this.modelSelect = new import_obsidian.DropdownComponent(modelContainer);
    this.plugin.models.forEach((model) => {
      this.modelSelect.addOption(model.name, `${model.name} - ${model.description}`);
    });
    this.modelSelect.setValue(this.plugin.currentModel);
    this.modelSelect.onChange((value) => {
      this.plugin.currentModel = value;
    });
    this.chatContainer = contentEl.createDiv("chat-container");
    this.chatContainer.style.height = "400px";
    this.chatContainer.style.overflowY = "auto";
    this.chatContainer.style.border = "1px solid var(--background-modifier-border)";
    this.chatContainer.style.padding = "10px";
    this.chatContainer.style.marginBottom = "10px";
    const inputContainer = contentEl.createDiv("input-container");
    this.inputElement = new import_obsidian.TextComponent(inputContainer);
    this.inputElement.inputEl.placeholder = "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0432\u0430\u0448 \u0432\u043E\u043F\u0440\u043E\u0441...";
    this.inputElement.inputEl.style.width = "70%";
    this.inputElement.inputEl.addEventListener("keypress", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    const sendButton = new import_obsidian.ButtonComponent(inputContainer);
    sendButton.setButtonText("\u041E\u0442\u043F\u0440\u0430\u0432\u0438\u0442\u044C");
    sendButton.onClick(() => this.sendMessage());
    const buttonContainer = contentEl.createDiv("button-container");
    buttonContainer.style.marginTop = "10px";
    const saveButton = new import_obsidian.ButtonComponent(buttonContainer);
    saveButton.setButtonText("\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0447\u0430\u0442");
    saveButton.onClick(() => this.saveChat());
    const clearButton = new import_obsidian.ButtonComponent(buttonContainer);
    clearButton.setButtonText("\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C");
    clearButton.onClick(() => this.clearChat());
  }
  async sendMessage() {
    const message = this.inputElement.getValue().trim();
    if (!message)
      return;
    this.addMessage("user", message);
    this.inputElement.setValue("");
    const loadingEl = this.chatContainer.createDiv("loading-message");
    loadingEl.textContent = "\u{1F916} \u0414\u0443\u043C\u0430\u044E...";
    try {
      const messages = this.conversation.map((msg) => ({
        role: msg.role,
        content: msg.content
      }));
      const response = await this.plugin.communicateWithAI(this.plugin.currentModel, messages);
      loadingEl.remove();
      if (response.error) {
        this.addMessage("assistant", `\u041E\u0448\u0438\u0431\u043A\u0430: ${response.error}`);
      } else if (response.choices && response.choices[0] && response.choices[0].message) {
        this.addMessage("assistant", response.choices[0].message.content);
      } else {
        this.addMessage("assistant", "\u041F\u043E\u043B\u0443\u0447\u0435\u043D \u043D\u0435\u043E\u0436\u0438\u0434\u0430\u043D\u043D\u044B\u0439 \u043E\u0442\u0432\u0435\u0442 \u043E\u0442 API");
      }
    } catch (error) {
      loadingEl.remove();
      this.addMessage("assistant", `\u041E\u0448\u0438\u0431\u043A\u0430: ${error}`);
    }
  }
  addMessage(role, content) {
    const message = {
      role,
      content,
      timestamp: new Date()
    };
    this.conversation.push(message);
    const messageEl = this.chatContainer.createDiv("chat-message");
    messageEl.addClass(role === "user" ? "user-message" : "assistant-message");
    const roleIcon = role === "user" ? "\u{1F464}" : "\u{1F916}";
    const roleText = role === "user" ? "\u0412\u044B" : "\u0418\u0418";
    messageEl.innerHTML = `
			<div class="message-header">
				<strong>${roleIcon} ${roleText}</strong>
				<small>${message.timestamp.toLocaleTimeString("ru-RU")}</small>
			</div>
			<div class="message-content">${content}</div>
		`;
    this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
  }
  async saveChat() {
    if (this.conversation.length === 0) {
      new import_obsidian.Notice("\u041D\u0435\u0442 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0439 \u0434\u043B\u044F \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F");
      return;
    }
    const title = `\u0427\u0430\u0442 \u0441 ${this.plugin.currentModel}`;
    await this.plugin.saveConversationToNote(this.conversation, title);
  }
  clearChat() {
    this.conversation = [];
    this.chatContainer.empty();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var QuickQuestionModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u043E\u043F\u0440\u043E\u0441 \u0418\u0418" });
    const modelContainer = contentEl.createDiv();
    modelContainer.createEl("label", { text: "\u041C\u043E\u0434\u0435\u043B\u044C: " });
    this.modelSelect = new import_obsidian.DropdownComponent(modelContainer);
    this.plugin.models.forEach((model) => {
      this.modelSelect.addOption(model.name, `${model.name} - ${model.description}`);
    });
    this.modelSelect.setValue(this.plugin.currentModel);
    const inputContainer = contentEl.createDiv();
    inputContainer.createEl("label", { text: "\u0412\u0430\u0448 \u0432\u043E\u043F\u0440\u043E\u0441:" });
    this.inputElement = new import_obsidian.TextComponent(inputContainer);
    this.inputElement.inputEl.placeholder = "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0432\u0430\u0448 \u0432\u043E\u043F\u0440\u043E\u0441...";
    this.inputElement.inputEl.style.width = "100%";
    this.inputElement.inputEl.style.height = "100px";
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.marginTop = "10px";
    const askButton = new import_obsidian.ButtonComponent(buttonContainer);
    askButton.setButtonText("\u0421\u043F\u0440\u043E\u0441\u0438\u0442\u044C");
    askButton.setCta();
    askButton.onClick(() => this.askQuestion());
    const cancelButton = new import_obsidian.ButtonComponent(buttonContainer);
    cancelButton.setButtonText("\u041E\u0442\u043C\u0435\u043D\u0430");
    cancelButton.onClick(() => this.close());
  }
  async askQuestion() {
    const question = this.inputElement.getValue().trim();
    if (!question) {
      new import_obsidian.Notice("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0432\u043E\u043F\u0440\u043E\u0441");
      return;
    }
    const selectedModel = this.modelSelect.getValue();
    try {
      const messages = [{ role: "user", content: question }];
      const response = await this.plugin.communicateWithAI(selectedModel, messages);
      if (response.error) {
        new import_obsidian.Notice(`\u041E\u0448\u0438\u0431\u043A\u0430: ${response.error}`);
        return;
      }
      if (response.choices && response.choices[0] && response.choices[0].message) {
        const answer = response.choices[0].message.content;
        const conversation = [
          { role: "user", content: question, timestamp: new Date() },
          { role: "assistant", content: answer, timestamp: new Date() }
        ];
        await this.plugin.saveConversationToNote(conversation, "\u0411\u044B\u0441\u0442\u0440\u044B\u0439 \u0432\u043E\u043F\u0440\u043E\u0441");
        new import_obsidian.Notice("\u041E\u0442\u0432\u0435\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0443");
        this.close();
      } else {
        new import_obsidian.Notice("\u041F\u043E\u043B\u0443\u0447\u0435\u043D \u043D\u0435\u043E\u0436\u0438\u0434\u0430\u043D\u043D\u044B\u0439 \u043E\u0442\u0432\u0435\u0442 \u043E\u0442 API");
      }
    } catch (error) {
      new import_obsidian.Notice(`\u041E\u0448\u0438\u0431\u043A\u0430: ${error}`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var PollinationsAISettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Pollinations AI" });
    new import_obsidian.Setting(containerEl).setName("\u041C\u043E\u0434\u0435\u043B\u044C \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setDesc("\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u043C\u043E\u0434\u0435\u043B\u044C \u0418\u0418 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").addDropdown((dropdown) => {
      this.plugin.models.forEach((model) => {
        dropdown.addOption(model.name, `${model.name} - ${model.description}`);
      });
      dropdown.setValue(this.plugin.settings.defaultModel);
      dropdown.onChange(async (value) => {
        this.plugin.settings.defaultModel = value;
        this.plugin.currentModel = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u0421\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C \u0447\u0430\u0442\u044B \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0438").setDesc("\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C \u0440\u0430\u0437\u0433\u043E\u0432\u043E\u0440\u044B \u0441 \u0418\u0418 \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0438").addToggle((toggle) => toggle.setValue(this.plugin.settings.saveToNotes).onChange(async (value) => {
      this.plugin.settings.saveToNotes = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u041F\u0430\u043F\u043A\u0430 \u0434\u043B\u044F \u0437\u0430\u043C\u0435\u0442\u043E\u043A").setDesc("\u041F\u0430\u043F\u043A\u0430, \u043A\u0443\u0434\u0430 \u0431\u0443\u0434\u0443\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C\u0441\u044F \u0447\u0430\u0442\u044B \u0441 \u0418\u0418").addText((text) => text.setPlaceholder("AI \u0427\u0430\u0442\u044B").setValue(this.plugin.settings.notesFolder).onChange(async (value) => {
      this.plugin.settings.notesFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API \u0442\u043E\u043A\u0435\u043D").setDesc("\u0422\u043E\u043A\u0435\u043D \u0434\u043B\u044F \u0434\u043E\u0441\u0442\u0443\u043F\u0430 \u043A API (\u0435\u0441\u043B\u0438 \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F)").addText((text) => text.setPlaceholder("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u043E\u043A\u0435\u043D...").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
      this.plugin.settings.apiToken = value;
      await this.plugin.saveSettings();
    }));
  }
};
